#! /usr/bin/python
# -*- Mode: Python; indent-tabs-mode: nil; tab-width: 4; coding: utf-8 -*-
# bcnote
#
# Copyright © 2015 Gwendal Le Bihan
# 
# This file is part of BCNote.
# 
# BCNote is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# BCNote is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with BCNote.  If not, see <http://www.gnu.org/licenses/>.

import gettext
gettext.install("bcnote", "/usr/share/locale")

from BCNote.informations import *
from BCNote.main import Application
import optparse
import logging

if __name__ == "__main__":
    optparser = optparse.OptionParser()
    optparser.add_option('--dev-mode', dest = "devMode", action="store_true", help = _("Development mode"))
    optparser.add_option('--dev-token', dest = "devToken", help = _("Specify dev token (dev)"))
    optparser.add_option('-d', '--debug-level', dest = "debugLevel", default = 1, help = _("Set debug level"), type = int)
    options, args = optparser.parse_args()
    
    if options.debugLevel > 4:
        options.debugLevel = 4
    if options.debugLevel < 0:
        options.debugLevel = 0
    
    if options.debugLevel == 4:
        logging.getLogger().setLevel(logging.DEBUG)
    elif options.debugLevel == 3:
        logging.getLogger().setLevel(logging.INFO)
    elif options.debugLevel == 2:
        logging.getLogger().setLevel(logging.WARNING)
    elif options.debugLevel == 1:
        logging.getLogger().setLevel(logging.ERROR)
    elif options.debugLevel == 0:
        logging.getLogger().setLevel(logging.CRITICAL)
        
    Application(options).run()
